### ISSUE TITLE
conversion broken

### ISSUE THREAD

**Issue by Tecnico1931** [stream-monkey/aws-transcribe-to-vtt#1]
Now that transcribe is out to the general public seems they have changed some punctuations and broken this.

**Comment by clarter** [comment]
I noticed this too. The issue seems to be with files that end with punctuation but no start time.

`      {
        "alternatives": [
          {
            "content": "."
          }
        ],
        "type": "punctuation"
      }`

If I remove that portion from the end of the file the conversion works.

**Comment by clarter** [comment]
I should have checked the pull requests first, looks like there is a fix for this:
https://github.com/stream-monkey/aws-transcribe-to-vtt/pull/3

**Comment by paullegrand** [comment]
Pull request that I just merged (#3) should fix this!
