### ISSUE TITLE
are you open to improvement pull requests?

### ISSUE THREAD

**Issue by mreinstein** [stream-monkey/aws-transcribe-to-vtt#4]
some things I'd like to change:

* use `const` and `let` instead of `var`
* make this usable as a library (I'd like to be able to use the conversion function)
* support es modules
* simplify project/file structure

if you'd be open to these I'd be happy to send along some PRs

**Comment by paullegrand** [comment]
Sure thing! I'll take a look through any PRs you make

**Comment by mreinstein** [comment]
@paullegrand I just submitted a PR for this (#5 )

Should make it a re-usable module now, and provide documentation on the API. Also simplified the interface quite a bit, and updated the dependencies.

Hope this helps! Thanks for a great module!

**Comment by mreinstein** [comment]
@paullegrand  I've closed the old one and submitted an updated PR. This PR makes less changes to your project structure and should be easier to integrate. 

Open to feedback etc.
